In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/row/credit_risk_dataset.csv")
df.shape

(32581, 12)

In [4]:
column_mapping = {
    "person_age": "age",
    "person_income": "income",
    "person_home_ownership": "home_ownership",
    "person_emp_length": "employment_years",
    "loan_intent": "loan_purpose",
    "loan_grade": "loan_grade",
    "loan_amnt": "loan_amount",
    "loan_int_rate": "interest_rate",
    "loan_status": "default",
    "loan_percent_income": "loan_income_ratio",
    "cb_person_default_on_file": "previous_default",
    "cb_person_cred_hist_length": "credit_history_years"
}

df = df.rename(columns=column_mapping)

df.head()

,age,income,home_ownership,employment_years,loan_purpose,loan_grade,loan_amount,interest_rate,default,loan_income_ratio,previous_default,credit_history_years
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
print(df.isnull().sum())

age                        0
income                     0
home_ownership             0
employment_years         895
loan_purpose               0
loan_grade                 0
loan_amount                0
interest_rate           3116
default                    0
loan_income_ratio          0
previous_default           0
credit_history_years       0
dtype: int64

In [6]:
numerical_columns = [
    "age",
    "income",
    "employment_years",
    "loan_amount",
    "interest_rate",
    "loan_income_ratio",
    "credit_history_years"
]

categorical_columns = [
    "home_ownership",
    "loan_purpose",
    "loan_grade",
    "previous_default"
]

for column in numerical_columns:
    df[column] = df[column].fillna(df[column].median())

for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   32581 non-null  int64
 1   income                32581 non-null  int64
 2   home_ownership        32581 non-null  str
 3   employment_years      32581 non-null  float64
 4   loan_purpose          32581 non-null  str
 5   loan_grade            32581 non-null  str
 6   loan_amount           32581 non-null  int64
 7   interest_rate         32581 non-null  float64
 8   default               32581 non-null  int64
 9   loan_income_ratio     32581 non-null  float64
 10  previous_default      32581 non-null  str
 11  credit_history_years  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.5 MB

In [13]:
df.duplicated().sum()

np.int64(165)

In [16]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [22]:
df[df["age"] < 18]
df[df["age"] > 100]

,age,income,home_ownership,employment_years,loan_purpose,loan_grade,loan_amount,interest_rate,default,loan_income_ratio,previous_default,credit_history_years
81,144,250000,RENT,4.0,VENTURE,C,4800,13.57,0,0.02,N,3
183,144,200000,MORTGAGE,4.0,EDUCATION,B,6000,11.86,0,0.03,N,2
575,123,80004,RENT,2.0,EDUCATION,B,20400,10.25,0,0.25,N,3
747,123,78000,RENT,7.0,VENTURE,B,20000,10.99,0,0.26,N,4
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25

In [23]:
df = df[(df["age"] >= 18) & (df["age"] <= 100)]

In [24]:
print("Minimum age:", df["age"].min())
print("Maximum age:", df["age"].max())

Minimum age: 20
Maximum age: 94

In [26]:
print(df[df["income"] <= 0])
print(df[df["loan_amount"] <= 0])
print(df[df["employment_years"] < 0])
print(df[df["credit_history_years"] < 0])

Empty DataFrame
Columns: [age, income, home_ownership, employment_years, loan_purpose, loan_grade, loan_amount, interest_rate, default, loan_income_ratio, previous_default, credit_history_years]
Index: []
Empty DataFrame
Columns: [age, income, home_ownership, employment_years, loan_purpose, loan_grade, loan_amount, interest_rate, default, loan_income_ratio, previous_default, credit_history_years]
Index: []
Empty DataFrame
Columns: [age, income, home_ownership, employment_years, loan_purpose, loan_grade, loan_amount, interest_rate, default, loan_income_ratio, previous_default, credit_history_years]
Index: []
Empty DataFrame
Columns: [age, income, home_ownership, employment_years, loan_purpose, loan_grade, loan_amount, interest_rate, default, loan_income_ratio, previous_default, credit_history_years]
Index: []

In [29]:
df.to_csv(
    "../data/processed/cleaned_data.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.